### ISSUE TITLE
How do I know the default awx admin password

### ISSUE THREAD

**Issue by ManMaster** [powertim/deploy_awx-rpm#2]
I used your project to deploy a clustered awx, but how do I know the awx admin password to login? I found in master_init role there has a task named "Generate password for AWX admin user", can this task password variable be passed as a configured parameter？

**Comment by powertim** [comment]
Hi, 
Thanks for your feedback.
The password is displayed during playbook execution.
But yes it could be defined by a var in group_vars/nodes.yml for example.
Let me know if you need further help.

And sorry for the delay, I totally forgot to check issues on this project.

**Comment by powertim** [comment]
So then you just need to remove these lines:

```
- name: Generate password for AWX admin user
    set_fact:
      password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"

  - name : Display password for AWX admin user
    debug:
      msg: "Randomly generated password for AWX admin user is : {{ password }}"
```

And add:

```
password: yourcleartextpassword
```

in file: group_vars/nodes.yml

**Comment by ManMaster** [comment]
yeah I see， Thanks
