### ISSUE TITLE
subscription-manager was not found in PATH on CentOS 7

### ISSUE THREAD

**Issue by patsevanton** [powertim/deploy_awx-rpm#7]
Hello! I try run deploy_awx-rpm on nodes CentOS 7.

Version
```
cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
```

Error:
```
TASK [db_prereqs : Activate Satellite repositories] ********************************************************************************************
failed: [172.26.9.163] (item=rhel-server-rhscl-7-rpms) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "item": "rhel-server-rhscl-7-rpms"
}

MSG:

The executable file subscription-manager was not found in PATH
```

**Comment by patsevanton** [comment]
Repository https://github.com/nizarlazuardy/deploy_awx-rpm don`t have this error.

![image](https://user-images.githubusercontent.com/10828883/75628282-a4edec00-5c01-11ea-8572-5f4c210124dc.png)

**Comment by powertim** [comment]
Hi, if you don't use Satellite you need to customize the playbook to use alternate sources and enable repositories.
